version: '2.1'
services:
    queue:
        image: rabbitmq:3-management
        restart: always
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
        ports:
            - "8081:15672"

    postgres:
        image: postgres:9.6
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASS}
            - POSTGRES_DB=${POSTGRES_DB}
        # Uncomment these lines to persist data on the local filesystem.
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - ${LOCAL_PG}:/var/lib/postgresql/data:Z

    webserver:
        image: kubistmi/airflow:2.0
        restart: always
        depends_on:
            - postgres
            - queue
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver ${AIRFLOW_USER} ${AIRFLOW_EMAIL} ${AIRFLOW_FIRST} ${AIRFLOW_LAST} ${AIRFLOW_PASS}
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: kubistmi/airflow:2.0
        restart: always
        depends_on:
            - queue
        environment:
            - EXECUTOR=Celery
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: kubistmi/airflow:2.0
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: kubistmi/airflow:2.0
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker
